### ISSUE TITLE
Add linux_ppc64 support 

### ISSUE THREAD

**Issue by aszalucha** [fommil/netlib-java#101]
Is it possible to easily compile it for ppc64 linux? There is lack of any instruction in the repository

**Comment by fommil** [comment]
I only do custom builds on a commercial basis - it is not trivial and requires access to the target hardware. You need to read and understand the `pom.xml` files to be able to do this yourself.

**Comment by edelsohn** [comment]
VMs on POWER8 systems running PPC64 Linux are available to Open Source developers. Why was the issue closed?

**Comment by fommil** [comment]
because I'm not interested in fixing this without financial remuneration.

**Comment by edelsohn** [comment]
If you weren't so quick to close this, you might have learned that IBM is offering bounties to fix issues, which is why @aszalucha opened the issue and recommended a bounty.

**Comment by fommil** [comment]
@edelsohn probably insignificant compared to my day rate. If you want this fixed, contact me directly and pay me real commercial rates. I'm not a charity.
