### ISSUE TITLE
Setting number of threads

### ISSUE THREAD

**Issue by luiarthur** [fommil/netlib-java#105]
Hi,

Is it possible to change the number of threads that openblas uses at run time?

For instance, when using openblas in C++, you can temporarily change the number of threads that openblas subroutines use by `openblas_set_num_threads(1);`. Is there an equivalent in netlib-java? I'm using the scala breeze and want to do something like:

```scala
val Xs = (1 to 1000).map( x => DenseMatrix.rand(200,200) )
Xs.toList.par.foreach( x => x.t * x )
```

Here `x.t *x` uses all cores on my machine. It would be nice if the matrix computations here would use 1 thread (instead of all) so I can use the threads to get the 1000 `x.t * x` 's in parallel.

**Comment by fommil** [comment]
This is a concern of your system implementation.
