### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by debasish83** [fommil/netlib-java#106]
Following https://github.com/fommil/netlib-java/issues/62:

I am also having the same issue on CentOS 6.5 GCC 4.4.7

ldd: warning: you do not have execution permission for ./netlib-native_system-linux-x86_64.so' ./netlib-native_system-linux-x86_64.so: /usr/lib64/libgfortran.so.3: versionGFORTRAN_1.4' not found (required by ./netlib-native_system-linux-x86_64.so)

I installed GCC 4.8.2 through devtools and linked the libgfortran.so.3 to libgfortran.so and then I am getting the following errors:

./netlib-native_system-linux-x86_64.so: error while loading shared libraries: /usr/lib64/libgfortran.so.3: invalid ELF header

Should I install GCC 4.8 directly from the source and not use the devtools ?

**Comment by fommil** [comment]
Hi, sorry I only answer support questions about netlib-java under a commercial contract. This is not a bug.

**Comment by debasish83** [comment]
I could recompile it for CentOS 6.5 with gcc 4.4. We are migrating to CentOS 7.2 but for now we will publish netlib-java internally for CentOS 6.5 and load it on Breeze and Spark. I will report on the runtime numbers. Cholesky was horrible on f2J (around 12 second on 4096 rank compare to 0.5 second on Mac). I am hoping OpenBLAS native cholesky will be at part with Mac's veclib. Thanks for the well structured repository. Native on Java/Scala is always tricky. We are using netlib-java heavily for Spark neural net but did you know if there were any benchmarks with nd4j with netlib-java ?
