### ISSUE TITLE
Fail to build: 1.2-SNAPSHOT not found

### ISSUE THREAD

**Issue by heroxbd** [fommil/netlib-java#116]
I downloaded netlib-java-1.2.2.tar.gz from

  https://github.com/fommil/netlib-java/archive/1.1.2.tar.gz

uncompressed and executed `mvn compile`. Then I get the following error message:

`[ERROR] Plugin com.github.fommil.netlib:generator:1.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT in sonatype-plugins-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]`

Any hints?

Actually, no netlib is found in sonatype snapshot: https://oss.sonatype.org/content/repositories/snapshots/com/github/fommil/

**Comment by fommil** [comment]
This is literally documented in the README.

**Comment by heroxbd** [comment]
Sorry I read the REAMDE, it already have
```xml
    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

In the pom.xml.   But it does not work.  Which part of the README are you referring to?

**Comment by fommil** [comment]
this is in bold text on the README.
