### ISSUE TITLE
Arrays with more than 2^31-1 elements

### ISSUE THREAD

**Issue by ZizhengTai** [fommil/netlib-java#117]
Correct me if I'm wrong, but it seems currently there is no way to operate on "arrays" with more than 2^31-1 elements, since `netlib-java`'s API uses Java arrays, which are indexed with 32-bit signed `int`s. Our current work involves huge matrices and we don't know how we can overcome this limitation.

Is it possible for the API to switch from Java arrays to a custom array type indexed with `long`s?

**Comment by fommil** [comment]
Nope.
