### ISSUE TITLE
Use JNR for the native components

### ISSUE THREAD

**Issue by DemiMarie** [fommil/netlib-java#118]
This is a feature request to use JNR to access the native functions.

**Comment by fommil** [comment]
Why? And does it allow primitive critical array access?

You should know that I only work on this project under a commercial contract.

**Comment by DemiMarie** [comment]
@fommil no.  I guess my real issue is that there is no good way to debug failure to load native system libraries (I couldn't figure out how to do so).

**Comment by fommil** [comment]
There would be absolutely no performance advantage without critical array pass through. Use the java impl if you have trouble, and if you need help beyond that I can only help with a contract in place.
