### ISSUE TITLE
Error Failure to find com.github.fommil.netlib:all:jar:1.1.2 always

### ISSUE THREAD

**Issue by zarzen** [fommil/netlib-java#125]
Hi I am building a software depending on netlib-java, and it depends on module all. 
I have checked on central repository(https://repo.maven.apache.org/maven2/com/github/fommil/netlib/all/1.1.2/). It doesn't have corresponding jars, only pom files there. I have tried search online the jars but haven't found it yet. 
Then I try to build jars and place them under ~/.m2/repositories/, same error then. I also found similar issues under such topic. I know that you recommend we use jars you published. While I just can't find it. Could you explain how to deal with?

Thanks

**Comment by fommil** [comment]
Please read the Installation part of the documentation and copy/paste it if necessary.

I bet you're missing `<type>pom</type>`.

**Comment by zarzen** [comment]
Hi I did confirm that it has the `<type>pom</type>` tag in `pom.xml`. I am building Spark Velox(https://github.com/amplab/velox-modelserver), which depends on keystoneml_2.10. The Velox itself doesn't contain dependency 
```
        <dependency>
            <groupId>com.github.fommil.netlib</groupId>
            <artifactId>all</artifactId>
            <version>1.1.2</version>
            <type>pom</type>
        </dependency>
```
But `keystoneml` has one.
