### ISSUE TITLE
Drop tag for version 1.1.2

### ISSUE THREAD

**Issue by ghisvail** [fommil/netlib-java#127]
Please consider dropping the tag for version `1.1.2`. Both tags `1.1.1` and `1.1.2` point at the same commit (https://github.com/fommil/netlib-java/commit/0b1c7833291af036291558f97c9277895700b8a7), the latter referencing version `1.1.1`. Tagged releases are used as source for upstream code in Linux packaging, hence the request.

Cheers,

**Comment by fommil** [comment]
it is the truth. 1.1.1 was a bad (binary dep) release. I really don't agree that you should be distributing these jars this way, it runs contrary to the way the entire JVM ecosystem works. If you have customers paying you for this service, I would appreciate some of the profits.

**Comment by ghisvail** [comment]
> 1.1.1 was a bad (binary dep) release

Did you read what I wrote? I am talking about the [**tags**](https://github.com/fommil/netlib-java/tags), not the binary releases. Both tags `1.1.1` and `1.1.2` point at **the very same commit**, so one of them is most likely wrong.

> I really don't agree that you should be distributing these jars this way, it runs contrary to the way the entire JVM ecosystem works.

I am talking about the source code here, not the jars.

> If you have customers paying you for this service, I would appreciate some of the profits.

This is completely off-topic to this issue, please read my opening statement again.

**Comment by fommil** [comment]
I understand you, and I'm telling you that the tags are correct: the jars were both created from the same commit but with different build environments. Fork this repo and use whatever tags you want, wherever you want them. I'm not interested in rewriting history to pander to an arbitrary build tool.
