### ISSUE TITLE
problem of using MKL within netlib-java

### ISSUE THREAD

**Issue by sproblvem** [fommil/netlib-java#62]
Hi, I am trying to use Spark with MKL. My OS distribution is CentOS 6.4, kernel version 2.6.32, 64-bit. I followed [the instruction](https://github.com/fommil/netlib-java#linux)  to setup MKL by add links

``` bash
$ cd /usr/lib64
$ sudo ln -sf /opt/intel/composer_xe_2013_sp1/mkl/lib/intel64/libmkl_rt.so libblas.so.3
$ sudo ln -sf /opt/intel/composer_xe_2013_sp1/mkl/lib/intel64/libmkl_rt.so liblapack.so.3
```

Contents of my `/etc/ld.so.conf` is

```
include ld.so.conf.d/*.conf
/usr/local/lib
/usr/lib64
```

and I had run `ldconfig` after I setup those links. But when I run spark, netlib-java give me this log :

```
14/05/13 23:14:44 WARN netlib.BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
14/05/13 23:14:44 WARN netlib.BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
```

I had add dependency to my `build.sbt`, but the WARN remained.

``` scala
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "1.0.0-SNAPSHOT",
  "org.apache.spark" %% "spark-mllib" % "1.0.0-SNAPSHOT",
  "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly()
)
```

Then I try to use MKL within MTJ, and MTJ give me similar WARNING.

```
$ mvn test -Dtest=DenseCholeskyTest
.......
Running no.uib.cipr.matrix.DenseCholeskyTest
May 15, 2014 11:09:05 AM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
May 15, 2014 11:09:05 AM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.797 sec
......
```

Asking for advice, and thank you.

**Comment by ravi9** [comment]
Hi,
I have the same issue when trying to use Spark with MKL. 
How can I change org.netlib logging towards FINEST ?

Thank you.

**Comment by cre8ivejp** [comment]
Same issue here

15/07/10 04:09:53 WARN netlib.BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
15/07/10 04:09:53 WARN netlib.BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

**Comment by fommil** [comment]
Hi, these are standard Java questions, not specific to `netlib-java`. I recommend asking reading the Javadocs for your logging framework.

**Comment by ravi9** [comment]
Thank you fommil.
@cre8ivejp Try the following:
In this example, I build the jar "spark-testexample.jar" with maven dependency
```
<dependency>
	<groupId>com.github.fommil.netlib</groupId>
	<artifactId>all</artifactId>
	<version>1.1.2</version>
	<type>pom</type>
</dependency>
```

1. try specifying --driver-class-path /path/to/ur/jar in your spark-submit argument.
Example: spark-submit --class test.Example --master local[*] --driver-class-path /target/spark-testexample.jar --driver-memory 10g --executor-memory 10g /target/spark-testexample.jar

2. If that doest work, try the following:
In "spark-testexample.jar", you must have several .so files. If your system is linux, then extract "netlib-native_system-linux-x86_64.so" as follows:
```
$sudo jar xf spark-testexample.jar netlib-native_system-linux-x86_64.so
```
Once you have extracted the netlib-native_system-linux-x86_64.so from the jar, do the following:
```
$ ldd netlib-native_system-linux-x86_64.so
```
This should print something similar to the following:
```
$ ldd netlib-native_system-linux-x86_64.so
ldd: warning: you do not have execution permission for `./netlib-native_system-linux-x86_64.so'
        linux-vdso.so.1 =>  (0x00007fff243b6000)
        libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f8b88615000)
        libblas.so.3 => /usr/lib64/atlas/libblas.so.3 (0x00007f8b880a5000)
        liblapack.so.3 => /usr/lib64/atlas/liblapack.so.3 (0x00007f8b87883000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8b874ef000)
        libquadmath.so.0 => /usr/local/lib/../lib64/libquadmath.so.0 (0x00007f8b872b4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8b8702f000)
        libgcc_s.so.1 => /usr/local/lib/../lib64/libgcc_s.so.1 (0x00007f8b86e19000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8b86c15000)
        libf77blas.so.3 => /usr/lib64/atlas/libf77blas.so.3 (0x00007f8b869f5000)
        libcblas.so.3 => /usr/lib64/atlas/libcblas.so.3 (0x00007f8b867d5000)
        /lib64/ld-linux-x86-64.so.2 (0x00000034b6400000)
        libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00007f8b86179000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8b85f5b000)
```

If this is a problem with GFORTRAN, it will print a warning message like the following--  version `GFORTRAN_1.4' not found:
```
$ ldd netlib-native_system-linux-x86_64.so
ldd: warning: you do not have execution permission for `./netlib-native_system-linux-x86_64.so'
./netlib-native_system-linux-x86_64.so: /usr/lib64/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ./netlib-native_system-linux-x86_64.so)
        linux-vdso.so.1 =>  (0x00007fff1a9ff000)
        libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f119ed5a000)
        libblas.so.3 => /usr/lib64/atlas/libblas.so.3 (0x00007f119e7ea000)
        liblapack.so.3 => /usr/lib64/atlas/liblapack.so.3 (0x00007f119dfc8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f119dc34000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f119d9b0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f119d7ab000)
        libf77blas.so.3 => /usr/lib64/atlas/libf77blas.so.3 (0x00007f119d58c000)
        libcblas.so.3 => /usr/lib64/atlas/libcblas.so.3 (0x00007f119d36c000)
        /lib64/ld-linux-x86-64.so.2 (0x00000034b6400000)
        libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00007f119cd0f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f119caf2000)
```

If GFORTRAN is the issue, then update gcc to atleast 4.8, which includes gfortran v4.8
If you already have gfortran >4.8, then point  libgfortran.so.3  to the correct .so

3.  (@fommil correct me if I'm wrong in the following testing style.)
To test what has been loaded, in your program do the following:
```
import com.github.fommil.netlib.BLAS;
System.out.println(BLAS.getInstance().getClass().getName());
```
If it is correctly loaded, then it should print:
```
com.github.fommil.netlib.NativeSystemBLAS
```
if it does not load, then it will print:
```
15/07/09 09:56:04 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
15/07/09 09:56:04 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
com.github.fommil.netlib.F2jBLAS
```

**Comment by fommil** [comment]
https://github.com/fommil/netlib-java#machine-optimised-system-libraries

**To enable machine optimised natives in netlib-java, end-users make their machine-optimised libblas3 (CBLAS) and liblapack3 (Fortran) available as shared libraries at runtime.**

**Comment by debasish83** [comment]
I am also having the same issue on CentOS 6.5 GCC 4.4.7

ldd: warning: you do not have execution permission for `./netlib-native_system-linux-x86_64.so'
./netlib-native_system-linux-x86_64.so: /usr/lib64/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ./netlib-native_system-linux-x86_64.so)

I installed GCC 4.8.2 through devtools and linked the libgfortran.so.3 to libgfortran.so and then I am getting the following errors:

./netlib-native_system-linux-x86_64.so: error while loading shared libraries: /usr/lib64/libgfortran.so.3: invalid ELF header

Should I install GCC 4.8 directly from the source and not use the devtools ?

**Comment by debasish83** [comment]
This issue is resolved...I have regenerated netlib-java for CentOS 6.5 with gcc 4.4.7...

**Comment by rongqi79** [comment]
I am having a problem here:  Failed to load NativeSystemBLAS on worker node, but succeeded on master node.
I am using Mllib on a cluster (spark standalone). I followed the instructions here to use MKL within netlib-java. What might be the reason? we checked the symbolic links
