### ISSUE TITLE
OS X: Clean install can't find com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT

### ISSUE THREAD

**Issue by j2kun** [fommil/netlib-java#74]
I'm trying to install netlib-java on Mac OS X 10.9.5 with Java 1.6 installed. I have no previous netlib-java versions to cause conflicts.

steps to reproduce:
1. Download ZIP of the repository.
2. Clean install of maven using homebrew via http://stackoverflow.com/a/17481557/438830
3. run `$ mvn clean install`

expected result:
netlib-java installs without error

observed result:
The following lines in the maven output

    [WARNING] The POM for com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT is missing, no dependency information available
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] netlib for Java ................................... SUCCESS [0.447s]
    [INFO] core .............................................. FAILURE [0.008s]
    [INFO] netlib-java ....................................... SKIPPED
    [INFO] native_ref ........................................ SKIPPED
    [INFO] native_ref-java ................................... SKIPPED
    [INFO] netlib-native_ref-osx-x86_64 ...................... SKIPPED
    [INFO] netlib-native_ref-win-i686 ........................ SKIPPED
    [INFO] netlib-native_ref-win-x86_64 ...................... SKIPPED
    [INFO] native_system ..................................... SKIPPED
    [INFO] native_system-java ................................ SKIPPED
    [INFO] netlib-native_system-osx-x86_64 ................... SKIPPED
    [INFO] netlib-native_system-win-i686 ..................... SKIPPED
    [INFO] netlib-native_system-win-x86_64 ................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.169s
    [INFO] Finished at: Fri Jan 23 18:55:35 CST 2015
    [INFO] Final Memory: 7M/81M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Plugin com.github.fommil.netlib:generator:1.2-SNAPSHOT or one of its dependencies
    could not be resolved: Failure to find com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT in 
    https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, 
    resolution will not be reattempted until the update interval of sonatype-plugins-snapshots has
    elapsed or updates are forced -> [Help 1]
    ...

Please let me know if I'm installing it incorrectly. The README was unclear on the steps to install, although it did claim it supported OS X "out of the box."

**Comment by fommil** [comment]
Read the README again.

**Comment by avulanov** [comment]
Apparently, Sonatype's Snapshot Repository does not contain netlib jars. You need to change the version of generator in pom.xml from `${project.version}` to one of the versions that can be found in Maven central, e.g. `1.1.2`.

Sam, this information is missing in README, and can be found only in the main pom.xml.

**Comment by fommil** [comment]
That's because there is no version. Use stable. Why would you even want to do that?

**Comment by DreamFlasher** [comment]
Thank you  @avulanov - your comment was extremely helpful!
In order to do that I executed `find . -type f -name "pom.xml" -exec sed -i 's/1.2-SNAPSHOT/1.1.2/g' {} +` in root.

**Comment by fommil** [comment]
this is wrong on so many levels. If you insist on actually building your own cut of `netlib-java`, you should be at least be using the commit tagged as the release. Why you're rolling your own build, I have no idea, everything is published on maven central.

**Comment by DreamFlasher** [comment]
It might be wrong, but it works, which is the great advantage in contrast to your solution. The tag https://github.com/fommil/netlib-java/tree/1.1.2 also has the 1.2-SNAPSHOT version in it.

**Comment by fommil** [comment]
@DreamFlasher why are you unable to use official builds from maven central? Which is working for 100,000+ downloads per month.

1.1.2 was a release for only one submodule, hence not all poms were updated: https://github.com/fommil/netlib-java/commit/8bafea3d6478dedd0c0f9d1bcda47d8958c822cc

**Comment by avulanov** [comment]
@DreamFlasher You are welcome. I can find only few reasons to build Netlib-java from scratch. One of them would be to make it compatible with the older GCC if you have e.g. RedHat 6.3. Netlib-java binaries require `libgfortran.so.3` from GCC 4.8+. Though in this case I compile the new GCC instead.

**Comment by fommil** [comment]
@avulanov yes, only custom installs on unsupported hardware. I would never recommend this approach as the way to "install netlib-java" as it is near-on impossible to get right.

**Comment by ldmtwo** [comment]
@fommil On RedHat, CentOS, etc, we are having huge issues getting this working. There are too many dependencies to satisfy and this is the only one we are not making progress with. As people said above, it is difficult to get our custom library to load when F2jBLAS keeps getting loaded. Libgfortran 1.4 and other magic is needed. I can't even force it to load my desired library with any of these below or combinations. I also find myself building this from scratch. Branch 1.1 ... I mean 1.2-snapshot. The comments in the pom might be helpful. I'll know in a few hours. I hope you will listen to the issues people are having soon. ....Nope. Has anyone been able to build this from scratch? I'm using GCC 5.3 (built from source, which has at least gfort 1.4). Previously, we were using GCC 4.8. The dependencies were fixed and thoroughly tested to be working, but netlib is still loading the wrong .so files. I need to show Spark and Spark-perf using non-standard BLAS libs.   

-Dcom.github.fommil.netlib.BLAS=com.github.fommil.netlib.NativeRefBLAS 
-Dcom.github.fommil.netlib.LAPACK=com.github.fommil.netlib.NativeRefLAPACK 
-Dcom.github.fommil.netlib.ARPACK=com.github.fommil.netlib.NativeRefARPACK 
-Dcom.github.fommil.netlib.NativeSystemBLAS.natives=/opt/intel/mkl/lib/intel64/libmkl_rt.so  
-Dcom.github.fommil.netlib.NativeSystemBLAS.natives=/root/spark-perf/mllib-tests/target/netlib-native_system-linux-x86_64.so

**Comment by fommil** [comment]
I'm only supporting netlib-java on a commercial basis.

**Comment by fommil** [comment]
Especially when i get questions that I've explicitly answered in the README.

**Comment by fommil** [comment]
In bold text.
