### ISSUE TITLE
arpack_combined_all javadoc is a dependency

### ISSUE THREAD

**Issue by gtopper** [fommil/netlib-java#78]
I couldn't find information as to why that is, but it adds significant (almost 6MB) weight to our uber jar. I suppose there is a way for us to exclude this transitive dependency, at least in SBT assembly, but I wonder if this dependency is necessary to begin with.

**Comment by fommil** [comment]
the javadocs are needed to build netlib-java with `provided` scope. Sounds like a bug in sbt/ivy if you're pulling it in.

**Comment by gtopper** [comment]
Thanks for the quick answer. Looking at the POM file, I see
```xml
<dependencies>
        ...
        <dependency>
            <groupId>net.sourceforge.f2j</groupId>
            <artifactId>arpack_combined_all</artifactId>
            <classifier>javadoc</classifier>
        </dependency>
</dependencies>
```
So I wonder why would SBT _not_ pull it in?

**Comment by gtopper** [comment]
It looks like the dependency is "provided" in [the source pom](https://github.com/fommil/netlib-java/blob/master/pom.xml), but not so in the [artifact pom](https://repo1.maven.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom).

**Comment by fommil** [comment]
heh, maybe it's a maven bug.

**Comment by gtopper** [comment]
If so, it seems to still exist in the latest Maven (3.3.1). Please consider reopening this issue. I guess I'll have to work around it in my project for now, since my knowledge of Maven is limited.

**Comment by fommil** [comment]
I'll reopen, but mark blocked (upstream).

**Comment by fommil** [comment]
thinking about this again, it's definitely an upstream bug.
