### ISSUE TITLE
Windows native dll cannot load when submit to local

### ISSUE THREAD

**Issue by davidshen84** [fommil/netlib-java#79]
I use the *OpenBLAS* dll, and have configured my application to work in IDE. When I start my Spark application from IntelliJ IDE, I can see in the log that the native lib is loaded successfully.

But if I use **spark-submit** to start my application, the native lib still cannot be load. I checked the *Environment* tab in the Spark UI, and the **java.library.path** is set correctly.

**Comment by fommil** [comment]
This sounds like a spark environmental problem. You'd be best asking on the spark user's list as all I can do is point you at the netlib-java README which tells you everything that needs to be available, sorry.
