### ISSUE TITLE
netlib-java problem with ACML?

### ISSUE THREAD

**Issue by weixu02** [fommil/netlib-java#81]
Would netlib-java work with ACML on Ubuntu?

I linked the libacml.so to libblas.so.3 and liblapack.so.3, but get a runtime error: undefined symbol cblas_dgemm. Anything I am missing?

Thanks.

**Comment by fommil** [comment]
Try just the BLAS, I'm not sure which API they implement. Maybe ask on one of their forums to find out which library you need to link to, and confirm that they have CBLAS. If not, you might need to do something similar to nobles.
