### ISSUE TITLE
RHEL7 Support

### ISSUE THREAD

**Issue by hntd187** [fommil/netlib-java#87]
I've found that the compiled native libraries don't seem to run RHEL7, they will be loaded 

```
490744:29 Jul 2015 14:43:22,170 INFO main com.github.fommil.jni.JniLoader - successfully loaded /tmp/jniloader910396164099017756netlib-native_system-linux-x86_64.so
491698:29 Jul 2015 14:43:44,156 WARN main com.github.fommil.netlib.BLAS - Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
```

When the library is loaded the program crashes instantly, when they aren't loaded they run fine, but I can't figure out for the life of me to get netlib to pick up on my own blas packages. Do I just add them to the classpath? 

I have installed
blas
blas-devel
blas64
blas64-devel
lapack
lapack-devel
lapack64
lapack64-devel
atlas
atlas-devel

When the library is loaded and the program crashes I get nothing, no output, no stack trace, absolutely nothing. I have logging set to debug, so it's pretty chatty, but still nothing. Any insight into how to debug this and get it working? I have these all working fine on rhel6, but I'd like to have it working on rhel7 as well.

Here is my blas install in /lib64
```
-rw-r--r--. 1 root root 620624 Jan 26  2014 /lib64/libblas64.a
lrwxrwxrwx. 1 root root     18 Jul 29 15:30 /lib64/libblas64.so -> libblas64.so.3.4.2
lrwxrwxrwx. 1 root root     18 Jul 29 15:30 /lib64/libblas64.so.3 -> libblas64.so.3.4.2
lrwxrwxrwx. 1 root root     18 Jul 29 15:30 /lib64/libblas64.so.3.4 -> libblas64.so.3.4.2
-rwxr-xr-x. 1 root root 352496 Jan 26  2014 /lib64/libblas64.so.3.4.2
-rw-r--r--. 1 root root 633128 Jan 26  2014 /lib64/libblas.a
lrwxrwxrwx. 1 root root     16 Jul 29 15:30 /lib64/libblas.so -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root     16 Jul 29 11:20 /lib64/libblas.so.3 -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root     16 Jul 29 11:20 /lib64/libblas.so.3.4 -> libblas.so.3.4.2
-rwxr-xr-x. 1 root root 364792 Jan 26  2014 /lib64/libblas.so.3.4.2
```

Lapack also in /lib64
```
-rw-r--r--. 1 root root 10077952 Jan 26  2014 /lib64/liblapack64.a
-rw-r--r--. 1 root root 10077976 Jan 26  2014 /lib64/liblapack64_pic.a
lrwxrwxrwx. 1 root root       20 Jul 29 15:31 /lib64/liblapack64.so -> liblapack64.so.3.4.2
lrwxrwxrwx. 1 root root       20 Jul 29 15:31 /lib64/liblapack64.so.3 -> liblapack64.so.3.4.2
lrwxrwxrwx. 1 root root       20 Jul 29 15:31 /lib64/liblapack64.so.3.4 -> liblapack64.so.3.4.2
-rwxr-xr-x. 1 root root  5634136 Jan 26  2014 /lib64/liblapack64.so.3.4.2
-rw-r--r--. 1 root root  9921008 Jan 26  2014 /lib64/liblapack.a
-rw-r--r--. 1 root root  5994252 Jan 26  2014 /lib64/liblapacke.a
lrwxrwxrwx. 1 root root       19 Jul 29 15:31 /lib64/liblapacke.so -> liblapacke.so.3.4.2
lrwxrwxrwx. 1 root root       19 Jul 29 11:20 /lib64/liblapacke.so.3 -> liblapacke.so.3.4.2
lrwxrwxrwx. 1 root root       19 Jul 29 11:20 /lib64/liblapacke.so.3.4 -> liblapacke.so.3.4.2
-rwxr-xr-x. 1 root root  1965920 Jan 26  2014 /lib64/liblapacke.so.3.4.2
-rw-r--r--. 1 root root 10077952 Jan 26  2014 /lib64/liblapack_pic.a
lrwxrwxrwx. 1 root root       18 Jul 29 15:31 /lib64/liblapack.so -> liblapack.so.3.4.2
lrwxrwxrwx. 1 root root       18 Jul 29 11:20 /lib64/liblapack.so.3 -> liblapack.so.3.4.2
lrwxrwxrwx. 1 root root       18 Jul 29 11:20 /lib64/liblapack.so.3.4 -> liblapack.so.3.4.2
-rwxr-xr-x. 1 root root  5638312 Jan 26  2014 /lib64/liblapack.so.3.4.2
```
and atlas in 
```
/usr/lib64/atlas/libsatlas.so.3.10
/usr/lib64/atlas/libtatlas.so.3.10
/usr/lib64/atlas/libatlas.a
```

**Comment by fommil** [comment]
As RHEL 7 is a paywalled (and increasingly proprietary) platform, it is extremely unlikely that I will be able to do anything for you without a commercial engagement.

You can try to debug this yourself by extracting the binary that is attempting to link to your system implementation and run `ldd` on it. If that looks ok, then look inside your `libblas.so.3`, `liblapack.so.3` and `libgfortran3.so` and see if they are missing any symbols that are referred to.

One guess I have is that perhaps RHEL have gone and packaged CBLAS into the BLAS.

**Comment by fommil** [comment]
What about the reference native implementation? If that works, at least the fortran libs are linking OK. Also, read the README again closely to make sure you've followed all the steps.

**Comment by hntd187** [comment]
Well here is what I get from the extracted jar 

```
ldd netlib-native_system-linux-x86_64.so
	linux-vdso.so.1 =>  (0x00007ffff19ba000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f199fcaa000)
	libblas.so.3 => /usr/lib64/libblas.so.3 (0x00007f199fa51000)
	liblapack.so.3 => /usr/lib64/liblapack.so.3 (0x00007f199f1e6000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f199ee25000)
	libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x00007f199ebe9000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f199e8e6000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f199e6d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f19a0366000)
```

**Comment by hntd187** [comment]
and the reference implementation

```
ldd netlib-native_ref-linux-x86_64.so
	linux-vdso.so.1 =>  (0x00007fffb7926000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007fe8246f9000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fe824338000)
	libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x00007fe8240fb000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007fe823df9000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fe823be3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe82507d000)
```

**Comment by fommil** [comment]
Yeah, looks like you need to start inspecting symbols. Sounds like RHEL cocked up and broke backwards compact on these libraries.

**Comment by hntd187** [comment]
Okay, is it possible to just specify my own native libraries manually like this?

```
-Dcom.github.fommil.netlib.NativeSystemBLAS.natives=/lib64/libblas.so
-Dcom.github.fommil.netlib.NativeRefBlas.natives=/lib64/libblas.so
```

Or if that isn't correct, is it fine to just extract the shared objects from the jar and link to that via this method?

**Comment by fommil** [comment]
It sounds like there in a confusion here about what is going wrong. Your ldd shows that there is no linker problem (assuming you run Java apps in the same environment as your shell). The problem must therefore be an expectation problem: some symbols must be missing from RHEL's system libraries. To find them, you'll need to inspect the symbol lists against a working system or try to compile against the netlib natives with a test C app. You're going to have the get your hands dirty.

Specifying the natives in the properties as you have suggested makes no sense. The natives need to implement the netlib-java API, not BLAS/LAPACK..

One question you should really ask yourself is: do you really need the performance from system natives? And if you have an empirical answer to that question, you probably wouldn't be using ATLAS to be perfectly honest ;-) (I strongly recommend that you watch the talk I gave at Scala exchange last year, linked from the readme)

**Comment by hntd187** [comment]
I have what seems to be working now, but I'm unsure if my library is being loaded. I compiled OpenBLAS on the system and updated the alternatives for libblas and liblapack and I get this in my log 

````
14 Aug 2015 11:24:04,436 WARN Executor task launch worker-0 com.github.fommil.netlib.BLAS - Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
14 Aug 2015 11:24:04,470 INFO Executor task launch worker-0 com.github.fommil.jni.JniLoader - successfully loaded /tmp/jniloader3044167538019362070netlib-native_ref-linux-x86_64.so
````

I'm not sure if this is saying the loading of the library failed or the loaded was successful, could you shed some light on this?

**Comment by hntd187** [comment]
actually I added symlinks from lib64 to the openblas libraries and the warning disappeared, sounds like it's working, also the info about loading successfully still comes up.

**Comment by fommil** [comment]
`native_ref` is the reference implementation in Fortran. I recommend doing some performance testing as it is rarely of benefit.

You need `native_system` if you want to be using your OpenBLAS. Is that what you see after updating the symlinks?

**Comment by hntd187** [comment]
Yup, you're right it's loading the system now.

For reference the atlas blas and lapack libraries don't work out of the box it seems, but compiling with open blas seems to work.

````
14 Aug 2015 11:47:52,396 INFO main-EventThread com.github.fommil.jni.JniLoader - successfully loaded /tmp/jniloader2356580035481457001netlib-native_system-linux-x86_64.so
````

**Comment by fommil** [comment]
yeah, as I suspected it sounds like RHEL have screwed up the packaging of the libraries. At least they haven't broken binary compatibility, which is good news. OpenBLAS is much better than ATLAS anyway, outshined only by MKL.

Thanks for feeding back your conclusions.
