### ISSUE TITLE
breeze(netlib) overtakes my disk space (jniloader9085474522955594794netlib-native_ref-win-x86_64.dl)

### ISSUE THREAD

**Issue by danielkorzekwa** [fommil/netlib-java#89]
In my local dir c:\Users\korzekwad\AppData\Local\Temp\ I found hundreds of files named jniloader9085474522955594794netlib-native_ref-win-x86_64.dl, 6MB each,

any explanation? could netlib-java reuse the same dll for each run?

I asked David Hall from breeze (https://groups.google.com/forum/#!topic/scala-breeze/ojsrtbPnjI0_ but he suggested posting this question here.

**Comment by fommil** [comment]
You must be terminating the JVM forcefully or have a buggy runtime because it's flagged as delete on exit. You can manage the native lib location manually, read the docs for JNILoader.

**Comment by fommil** [comment]
Or don't use natives. Most people don't actually need natives.

**Comment by danielkorzekwa** [comment]
this is what I'm getting on runtime:

Sep 01, 2015 11:47:13 AM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Sep 01, 2015 11:47:14 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\KORZEK~1\AppData\Local\Temp\jniloader437420495990851267netlib-native_ref-win-x86_64.dll
Sep 01, 2015 11:47:14 AM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Sep 01, 2015 11:47:14 AM com.github.fommil.jni.JniLoader load
INFO: already loaded netlib-native_ref-win-x86_64.dll

**Comment by fommil** [comment]
thats all normal, see my comments above.
