### ISSUE TITLE
Additional Windows MKL library loading documentation

### ISSUE THREAD

**Issue by tgsoverly** [fommil/netlib-java#90]
Thanks for writing an excellent library.

I am in need of some extra performance and need it to run on the windows platform.  Do you have any additional information about using the MKL library for windows?  I totally understand that you are not responsible intel's package, but I am out of ideas.

I have specified the library with:
```		
def libraryName = "mkl_rt.dll"

System.setProperty("com.github.fommil.netlib.NativeSystemBLAS.natives", libraryName)

System.setProperty("com.github.fommil.netlib.NativeSystemLAPACK.natives", libraryName)
```

The system message from your loader says it successfully loads the library.  But then I get an `java.lang.UnsatisfiedLinkError: com.github.fommil.netlib.NativeSystemLAPACK.slamch(Ljava/lang/String;)F`, 

per your suggestion I used Dependency Walker and looked into the "mkl_rt.dll"

To my my eye it seems to be there:

<img width="638" alt="screen shot 2015-09-01 at 2 21 33 pm" src="https://cloud.githubusercontent.com/assets/482572/9612782/79c6aa28-50b5-11e5-8f6c-fc9e4f30034c.png">

Do you know if I need to do something silly I am missing?

**Comment by fommil** [comment]
sorry, I've actually never set this up on Windows MKL... when I had access to a windows box I just made sure it worked with the reference, ATLAS and openblas implementations.

note https://github.com/fommil/netlib-java#customisation specifically the bit in bold text, where I think you have gone wrong.

**Comment by fommil** [comment]
FWIW I think it should "just work" if you copy the MKL libs to files with these names, again note the docs:

> The native_system builds expect to find libblas3.dll and liblapack3.dll on the %PATH%

**Comment by tgsoverly** [comment]
Yea, I have tried both of those things as well.  I put it on the PATH and directly in System32, with the names above and not renaming.

**Comment by fommil** [comment]
if its anything like the Linux version, it is not enough to have that one file on your libpath, you'll also need to ensure that the OS knows about the entire MKL directory (plus the renaming is very important).
