### ISSUE TITLE
[ERROR] Plugin com.github.fommil.netlib:generator:1.2-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-plugins-snapshots has elapsed or updates are forced 

### ISSUE THREAD

**Issue by dbl001** [fommil/netlib-java#92]
I'm trying to build Spark 1.5 Snapshot with support for native libraries.

http://spark.apache.org/docs/latest/mllib-guide.html

"Dependencies
MLlib uses the linear algebra package Breeze, which depends on netlib-java for optimised numerical processing. If natives libraries1 are not available at runtime, you will see a warning message and a pure JVM implementation will be used instead.

Due to licensing issues with runtime proprietary binaries, we do not include netlib-java’s native proxies by default. To configure netlib-java / Breeze to use system optimised binaries, include com.github.fommil.netlib:all:1.1.2 (or build Spark with -Pnetlib-lgpl) as a dependency of your project and read the netlib-java documentation for your platform’s additional installation instructions."

I've read in other issues that netlib-java is not easy to build.  Should I just include the dependencies in Spark's pom.xml?

**Comment by fommil** [comment]
If you're not using the jars that I publish, you're on your own. In fact, I have absolutely no idea why you would ever try to compile `netlib-java`. https://github.com/fommil/netlib-java#installation
