### ISSUE TITLE
OpenBlas on OS/X

### ISSUE THREAD

**Issue by nogj** [fommil/netlib-java#93]
Hi,

I apologize in advance if this is a too basic question, but I'm not able to figure out how to configure netlib-java on OS/X to use an arbitrary BLAS implementation (e.g. OpenBLAS), other than the native one that is bundled with the operating system (VecLib)... is there any way to do it?

Best Regards, and thank you for your work,

--
Jorge

**Comment by fommil** [comment]
There is an entire section it the README specifically for this.
