### ISSUE TITLE
Receiving an Error while using Matrix-Toolkits-Java

### ISSUE THREAD

**Issue by vikramc1** [fommil/netlib-java#94]
I am currently managing a project using Maven on a Mac and am running OS 10.11 and attempting to use netlib-java but I keep getting the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/netlib/util/intW
Caused by: java.lang.ClassNotFoundException: org.netlib.util.intW

my pom.xml includes dependency to "all" version 1.1.2. Any help would be greatly appreciated.

**Comment by fommil** [comment]
Your maven config is definitely wrong, probably you disabled transitive deps.

**Comment by hmf** [comment]
For anyone encountering this problem with ivy/sbt: you need to add f2j explicitly.

    libraryDependencies += "net.sourceforge.f2j" % "arpack_combined_all" % "0.1"
    libraryDependencies += "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly()
    libraryDependencies += "com.googlecode.matrix-toolkits-java" % "mtj" % "1.0.4"

HTHs
