### ISSUE TITLE
Netlib does not respect system library path

### ISSUE THREAD

**Issue by bashimao** [fommil/netlib-java#95]
Well, to make a long story short. I would like to see netlib searching for its native dependencies like other applications.
i.e.: Respect the settings in /etc/ld.so.conf

**Comment by fommil** [comment]
It does. Sounds like you have a bad system config. You need a reproducible falling test case (use docker) to convince me otherwise.

**Comment by bashimao** [comment]
Is there a way to get the path of the loaded native library in code? I know there is a debug output, but I want to see if all my cluster nodes load my preferred native implementation.
