### ISSUE TITLE
Why doesn't Spark include the native proxies of netlib-java?

### ISSUE THREAD

**Issue by LeeTL1220** [fommil/netlib-java#96]
We would like to integrate the native code proxies of netlib-java into our project when running on Apache Spark MLLib.

However, when I look at the Spark documentation, I noticed some ominous language:

```
Due to licensing issues with runtime proprietary binaries, we do not include netlib-java’s native proxies by default.

```

(https://spark.apache.org/docs/1.5.1/mllib-guide.html)

I was curious what the issues are?

Thanks!

**Comment by fommil** [comment]
It is hardly ominous. Apache Spark can't distribute LGPL (e.g. jni-loader) or proprietary binaries (e.g. Intel MKL).
