### ISSUE TITLE
Work with JVM team on vectorized pure-Java implementation

### ISSUE THREAD

**Issue by almson** [fommil/netlib-java#97]
HotSpot has had some support for auto-vectorization for the past couple of years. See [this blog](http://psy-lob-saw.blogspot.com/2015/04/on-arraysfill-intrinsics-superword-and.html) and some more references on [StackOverflow](http://stackoverflow.com/questions/10784951/do-any-jvms-jit-compilers-generate-code-that-uses-vectorized-floating-point-ins).

I am not sure of the details. E.g., if it currently supports multiply-add, and how to write Java code that activates it.

It would be great for this project to reach out to and collaborate with the relevant JVM developers to ensure that one of the biggest applications of vectorization, BLAS, is addressed.

**Comment by fommil** [comment]
I've tried contacting people, but not got any response. If you have any contacts in that area, I'd be happy to talk to them, but I'm not sure what value would be added by having this support in the JDK... the real power comes from the backend implementation anyway and provisioning your JDK to have the correct load path is probably a lot harder than configuring a dynamic library.

**Comment by almson** [comment]
That's too bad. Relying on a native library is fine, but it would be very nice if a pure-Java implementation could get even 75% of native performance. Java in general is sorely in need of vectorization. It's a bit of a mystery to me why they are moving so slowly towards it and saying so little. I'll let you know if I get a hold of anyone who might be worthwhile.

**Comment by fommil** [comment]
@almson watch my talk and see why you won't get a benefit unless you have machine optimised binaries. It's not enough to link to any old "native BLAS", Java is faster than you think.

**Comment by almson** [comment]
Which talk? I'm not sure what you are trying to say. I understand what's involved in writing an optimized matrix multiplication.

**Comment by fommil** [comment]
The talk linked on the main page. I'd be amazed if you don't learn something from it. I learnt a lot writing it. Unless Oracle plan on shipping MKL, I really can't see an embedded BLAS actually improving anything.
