### ISSUE TITLE
Spark-Netlib interface

### ISSUE THREAD

**Issue by RoiViber** [fommil/netlib-java#98]
Hi

A short background: I've been struggling with the latest spark release (1.5.2) and netlib integration. It seems as Spark is constantly refusing to load netlib at all. I've already managed to work netlib out with OpenBLAS/Atlas on previous Spark versions but lately they decided to deprecate the SPARK_CLASSPATH variable, and I now need to find a way of hacking it into loading netlib before the default BLAS libraries.

* AWS machines come with atlas on them, in /usr/lib64/atlas/ specifically.
* note that dynamic links are in /usr/lib64 rather than /usr/lib (should that change to netlib?)
* I'm running spark on deploy-mode=local due to restrictions.

The steps I've gone through are as follows:
1. Added /usr/lib64/atlas/ in /etc/ld.so.conf
2. ldconfig -v | grep atlas - verifying that atlas libs are there ****
3. Added "export LD_LIBRARY_PATH=/usr/lib64/atlas/*:$LD_LIBRARY_PATH" to both: (a) spark-env.sh (b) ~/.bashrc (c) ran this command on the CLI
4. The last part I was missing from the old-but-working Spark release is Adding "export SPARK_CLASSPATH=/tmp/netlib/*:$SPARK_CALSSPATH". As I've mentioned, this variable is deprecated due to spark usage of spark.*.extraClasspath conf-arguments. So I tried spark.driver.extraClasspath=/tmp/netlib

Now, i've  compiled a small jar that loads breeze and uses some DenseMatrix multiplication, just to verify it is working. I keep getting the "WARN BLAS: Failed to load implementation from"  messages. 

To help debugging/hacking this through, can anyone tell me how do I know whether Netlib is loaded at all? is this a problem of pointing (or importing) the native libraries, or importing netlib?

**Comment by fommil** [comment]
You should ask on spark mailing lists. I don't have time to answer devops questions unless it's under a commercial arrangement.

**Comment by RoiViber** [comment]
Fair enough. Thanks for the fast reply. 

Does Netlib log some message that can be informative regarding whether is it used or not?

**Comment by fommil** [comment]
yes, it's all standard JUL logging. I don't know how you've set any of this up so I can't comment on how to change it. No doubt Spark does some magic with log messages.
