### ISSUE TITLE
System.setProperty( "com.github.fommil.netlib.BLAS", "com.github.fommil.netlib.F2jBLAS") not working for android

### ISSUE THREAD

**Issue by radiodee1** [fommil/netlib-java#99]
I am writing a trivial android app that uses netlib-java in it's dependencies. This is the dependencies line from the 'build.gradle' file:

        compile 'com.github.fommil.netlib:all:1.1.2' 

The app fails, with an error message that reads, in part:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/fommil/netlib/BLAS;

in the offending line `model.output(/* input here */) `
model is a multilayer convoutional neural network from deeplearning4j
using 0.4-rc3.9-SNAPSHOT from github. I have filed a bug on that github project.

I use the following lines to prepare netlib-java for android, where there is no GPU:

        String key1 = "com.github.fommil.netlib.BLAS";
        String prop1 = "com.github.fommil.netlib.F2jBLAS";

        String key2 = "com.github.fommil.netlib.LAPACK";
        String prop2 = "com.github.fommil.netlib.F2jLAPACK";

        String key3 = "com.github.fommil.netlib.ARPACK";
        String prop3 = "com.github.fommil.netlib.F2jARPACK";

        System.setProperty(key1, prop1);
        System.setProperty(key2, prop2);
        System.setProperty(key3, prop3);

        System.setProperty("org.nd4j.linalg.cpu.force_native","false");
        
A gist with the full error message is found here:

https://gist.github.com/radiodee1/3dcb89e4928e958f52f6

This is a link to the full android project:

https://github.com/radiodee1/awesome-cnn-android

It relies heavily on the LenetMnistExample from the cnn examples repository of deeplearning4j. It's not finished. No licenses yet, stuff like that. Hopefully you can help or direct me where to look for help. Thanks.

**Comment by fommil** [comment]
android is not supported, see the README.

**Comment by fommil** [comment]
(you should just be using the F2J implementation, I don't know why you're trying to load natives that are not there)

**Comment by radiodee1** [comment]
the F2j implementation crashes. That's the problem. Is this 
setProperty() line written wrong? I'm not loading anything. Should it be 
"F2JBLAS" to work?

**Comment by fommil** [comment]
```
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.fommil.netlib.BLAS"
```

this means you have not got the required jars on your classpath. It's not a bug in `netlib-java`.

Depending on `all` is wasteful on Android, you only need `core`.

**Comment by radiodee1** [comment]
thank you. replacing 'all' with 'core' stops that particular error. 
Thanks again.

**Comment by fommil** [comment]
hmm, I wonder if `gradle` is unable to correctly handle `pom` only projects.
